# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g truffle
    - run: npm install
    - run: truffle compile
    - run: echo "ROPSTEN_NODE_URL=${{ secrets.ROPSTEN_NODE_URL }}" >> .env
    - run: echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
    - run: echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
    - run: truffle migrate --network ropsten
    - run: truffle run verify VASP --network ropsten
    - run: truffle run verify VaspFactory --network ropsten
    - run: truffle run verify VaspBuilder --network ropsten
    - run: rm .env



